### ISSUE TITLE
Not compatible with IntelliJ IDEA 2023.2

### ISSUE THREAD

**Issue by mardukbp** [zowe/zowe-jcl-intellij#13]
I cannot install the plugin because it is not compatible with the latest version of IntelliJ IDEA. I hope it is only a matter of updating some XML file.

**Comment by KUGDev** [comment]
Resolved with https://github.com/zowe/zowe-jcl-intellij/commit/f61a8033c29a75aaf3da3055220fc22a2d5e655e
Wait for the update to appear at the Jetbrains Marketplace in a few hours

**Comment by mardukbp** [comment]
Awesome! Thank you :)
