### ISSUE TITLE
What about using JCL language server?

### ISSUE THREAD

**Issue by angelozerr** [zowe/zowe-jcl-intellij#19]
It seems IBM provides a JCL language server https://marketplace.visualstudio.com/items?itemName=IBM.zopeneditor

I wonder if you plan to do that?

**Comment by KUGDev** [comment]
@angelozerr the IBM Z Open Editor is a closed-source software
We are not going to base on this solution
We have some plans around the LSP usage in the future, but at the time we have some other priorities
The changes will be tracked here
https://github.com/zowe/zowe-jcl-intellij/issues/14
